wandb_version: 1

booster:
  desc: null
  value: gblinear
learning_rate:
  desc: null
  value: 0.1
max_depth:
  desc: null
  value: 12
subsample:
  desc: null
  value: 0.5
seed:
  desc: null
  value: 1234
text_size:
  desc: null
  value: 0.33
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.12
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1701402985.759742
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.11.4
      5: 0.15.12
      8:
      - 1
      - 2
      - 5
      13: darwin-x86_64
