name: cfb
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.7.1=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311h5547dcb_3
  - arrow=1.2.3=pyhd8ed1ab_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backoff=1.11.1=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - brotli=1.0.9=he49afe7_4
  - brotli-python=1.0.9=py311h814d153_9
  - bzip2=1.0.8=h0d85af4_4
  - ca-certificates=2023.7.22=h8857fd0_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py311ha86e640_3
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.2.0=py311h7bea37d_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.6.8=py311hdf8f085_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - duckdb-engine=0.9.2=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.2=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - flit-core=3.9.0=pyhd8ed1ab_0
  - fonttools=4.44.0=py311he705e18_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h60636b9_2
  - gettext=0.21.1=h8a4c099_0
  - giflib=5.2.1=hb7f2c08_3
  - glib=2.76.4=h7d26f99_0
  - glib-tools=2.76.4=h7d26f99_0
  - greenlet=3.0.1=py311hd39e593_0
  - gst-plugins-base=1.14.1=hcec6c5f_1
  - gstreamer=1.14.1=h6c40b1e_1
  - icu=58.2=h0a44026_1000
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.1=pyhd8ed1ab_0
  - ipykernel=6.25.1=pyh5fb750a_0
  - ipython=8.14.0=pyhd1c38e8_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.1.0=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=hb7f2c08_3
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.19.0=pyhd8ed1ab_1
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.19.0=pyhd8ed1ab_1
  - jupysql=0.10.1=pyhd8ed1ab_0
  - jupyter=1.0.0=py311h6eed73b_8
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter_client=8.3.0=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py311h6eed73b_0
  - jupyter_events=0.7.0=pyhd8ed1ab_2
  - jupyter_server=2.7.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=4.0.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.24.0=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.8=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py311h5fe6e05_1
  - krb5=1.20.1=h049b76e_0
  - lcms2=2.15=h29502cd_0
  - lerc=4.0.0=hb486fe8_0
  - libblas=3.9.0=17_osx64_openblas
  - libcblas=3.9.0=17_osx64_openblas
  - libclang=12.0.0=default_hbc2896b_2
  - libcxx=16.0.6=hd57cbcb_0
  - libdeflate=1.17=hb664fd8_0
  - libedit=3.1.20191231=h0678c8f_2
  - libexpat=2.5.0=hf0c8a7f_1
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=12_3_0_h97931a8_1
  - libgfortran5=12.3.0=hbd3c1fe_1
  - libglib=2.76.4=hc62aa5d_0
  - libiconv=1.17=hac89ed1_0
  - liblapack=3.9.0=17_osx64_openblas
  - libllvm12=12.0.1=hd011deb_2
  - libopenblas=0.3.23=openmp_h429af6e_0
  - libpng=1.6.39=ha978bb4_0
  - libpq=12.15=h04015c4_1
  - libsodium=1.0.18=hbcb3906_1
  - libsqlite=3.42.0=h58db7d2_0
  - libtiff=4.5.0=hee9004a_2
  - libwebp=1.2.4=h70a068d_1
  - libwebp-base=1.2.4=h6c40b1e_1
  - libxcb=1.13=h0d85af4_1004
  - libxml2=2.10.3=h930c0e2_0
  - libxslt=1.1.37=h5d22bc9_0
  - libzlib=1.2.13=h8a1eda9_5
  - llvm-openmp=16.0.6=hff08bdf_0
  - markupsafe=2.1.3=py311h2725bcf_0
  - matplotlib=3.8.1=py311h6eed73b_0
  - matplotlib-base=3.8.1=py311hd316c10_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=3.0.0=pyhd8ed1ab_0
  - monotonic=1.5=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.7.3=pyhd8ed1ab_0
  - nbconvert-core=7.7.3=pyhd8ed1ab_0
  - nbconvert-pandoc=7.7.3=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=hf0c8a7f_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=7.0.2=pyhd8ed1ab_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - nspr=4.35=hea0b92c_0
  - nss=3.89=h78b00b3_0
  - openjpeg=2.5.0=h13ac156_2
  - openssl=3.1.4=hd75f5a5_0
  - overrides=7.4.0=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandoc=3.1.3=h9d075a6_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.40=h1c4e4bc_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py311h5bae705_1
  - pip=23.2.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - ploomber-core=0.2.15=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pooch=1.7.0=pyha770c72_3
  - posthog=3.0.2=pyhd8ed1ab_0
  - prettytable=3.9.0=pyhd8ed1ab_0
  - prometheus_client=0.17.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py311h5547dcb_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyobjc-core=9.2=py311hf110eff_0
  - pyobjc-framework-cocoa=9.2=py311hf110eff_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyqt=5.15.7=py311hcec6c5f_0
  - pyqt5-sip=12.11.0=py311hcec6c5f_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.4=h30d4d87_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-duckdb=0.9.1=py311hba6cf09_0
  - python-fastjsonschema=2.18.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pyyaml=6.0=py311h5547dcb_5
  - pyzmq=25.1.1=py311h5dacc12_0
  - qt-main=5.15.2=h719ae48_7
  - qt-webengine=5.15.9=h90a370e_4
  - qtconsole=5.4.3=pyhd8ed1ab_0
  - qtconsole-base=5.4.3=pyha770c72_0
  - qtpy=2.3.1=pyhd8ed1ab_0
  - qtwebkit=5.212=hbfab81c_5
  - readline=8.2=h9e318b2_1
  - referencing=0.30.2=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.9.2=py311h299eb51_0
  - scipy=1.11.1=py311h16c3c4d_0
  - send2trash=1.8.2=pyhd1c38e8_0
  - setuptools=68.0.0=pyhd8ed1ab_0
  - sip=6.6.2=py311hcec6c5f_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlalchemy=2.0.23=py311he705e18_0
  - sqlglot=19.1.3=pyhd8ed1ab_0
  - sqlite=3.42.0=h2b0dec6_0
  - sqlparse=0.4.4=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.3.2=py311h2725bcf_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.6.1=pyhd8ed1ab_0
  - wheel=0.41.1=pyhd8ed1ab_0
  - widgetsnbextension=4.0.8=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=h0dc2134_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xz=5.4.2=h6c40b1e_0
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h8a1eda9_5
  - zstd=1.5.2=h829000d_7
  - pip:
    - cfbd==4.5.1
    - jaraco-classes==3.3.0
    - keyring==24.2.0
    - more-itertools==10.1.0
    - numpy==1.26.1
    - pandas==2.1.1
    - pytz==2023.3.post1
    - urllib3==2.0.6
prefix: /Users/Brian/opt/anaconda3/envs/cfb
